name: Check All Related PRs Status Across Repositories

on:
  pull_request:
    types: [opened, synchronize]  # Triggers on PR creation or updates
  workflow_dispatch:  # Allows manual/API triggering for rechecks

jobs:
  check-related-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Start - Extract Related PRs from Main PR Body
        id: extract_related_prs
        run: |
          echo "Step 1: Extracting related PR URLs from the main PR body..."

          # Extract URLs of related PRs from the PR body.
          # These URLs should follow the pattern https://github.com/<owner>/<repo>/pull/<number>.
          RELATED_PRS=$(echo "${{ github.event.pull_request.body }}" | grep -Eo 'https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/pull/[0-9]+' | tr '\n' ' ')

          # Check if we found any related PRs in the PR body.
          if [ -z "$RELATED_PRS" ]; then
            echo "No related PRs found in the PR body. Assuming no dependencies."
            echo "Marking all as merged since no PRs found."
            echo "all_merged=true" >> $GITHUB_ENV
            exit 0
          fi

          # Print the found related PRs.
          echo "Related PRs found: $RELATED_PRS"

          # Store the found related PRs as output to be used in the next step.
          echo "related_prs=$RELATED_PRS" >> $GITHUB_OUTPUT
          echo "Output set: Related PRs = $RELATED_PRS"

      - name: Print Extracted PRs for Debugging
        run: |
          # Debug step to print extracted PRs.
          echo "Debugging: Printing extracted related PRs."
          echo "Related PRs: ${{ steps.extract_related_prs.outputs.related_prs }}"

      - name: Start - Checking Status of Each Related PR
        run: |
          echo "Step 2: Checking the merge status of each related PR..."

      - name: Check Status of Each Related PR
        id: check_related_prs
        run: |
          # Initialize flag to track if all related PRs are merged.
          ALL_MERGED=true
          echo "Processing each related PR..."

          # Loop through each related PR URL extracted in the first step.
          for PR_URL in ${{ steps.extract_related_prs.outputs.related_prs }}; do
            echo "Checking status for PR: $PR_URL"

            # Extract the PR number and repository name from the URL.
            PR_NUMBER=$(basename "$PR_URL")
            REPO_FULL_NAME=$(echo "$PR_URL" | sed 's|https://github.com/||' | sed 's|/pull/.*||')

            echo "PR Number: $PR_NUMBER"
            echo "Repository: $REPO_FULL_NAME"

            # Fetch the PR status via the GitHub API.
            echo "Fetching merge status from GitHub API..."
            PR_STATUS=$(curl -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
              "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER" | jq -r '.merged')

            # Print the fetched PR status.
            echo "PR Merge Status: $PR_STATUS"

            # Check if the PR is merged or not.
            if [ "$PR_STATUS" != "true" ]; then
              ALL_MERGED=false
              echo "PR #$PR_NUMBER in repository $REPO_FULL_NAME is NOT merged."
            else
              echo "PR #$PR_NUMBER in repository $REPO_FULL_NAME is merged."
            fi
          done

          # Fail the job if any PR is not merged.
          if [ "$ALL_MERGED" != "true" ]; then
            echo "Not all related PRs are merged. Failing the check."
            exit 1
          else
            echo "All related PRs are merged. Success."
          fi

      - name: Final - Print Merge Status of All PRs
        run: |
          echo "Step 3: All related PRs have been successfully checked."
