name: Check All Related PRs Status Across Repositories

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:  # Allows manual/API triggering

jobs:
  check-related-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Start - Extract Related PRs from Main PR Body
        run: |
          echo "Step 1: Starting extraction of related PRs from the main PR body..."
          # Extract related PR URLs from the PR body
          RELATED_PRS=$(echo "${{ github.event.pull_request.body }}" | grep -Eo 'https://github.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/pull/[0-9]+' | tr '\n' ' ')

          if [ -z "$RELATED_PRS" ]; then
            echo "No related PRs found. Assuming no dependencies."
            echo "all_merged=true" >> $GITHUB_ENV
            exit 0
          fi

          echo "Related PRs found: $RELATED_PRS"
          echo "related_prs=$RELATED_PRS" >> $GITHUB_OUTPUT

      - name: Start - Checking Status of Each Related PR
        run: |
          echo "Step 2: Checking the merge status of each related PR..."

      - name: Check Status of Each Related PR
        id: check_related_prs
        run: |
          echo "Checking the merge status of the following PRs: ${{ steps.extract_related_prs.outputs.related_prs }}"

          ALL_MERGED=true
          for PR_URL in ${{ steps.extract_related_prs.outputs.related_prs }}; do
            echo "Checking PR: $PR_URL"
            PR_NUMBER=$(basename "$PR_URL")
            REPO_FULL_NAME=$(echo "$PR_URL" | sed 's|https://github.com/||' | sed 's|/pull/.*||')
            PR_STATUS=$(curl -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
              "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER" | jq -r '.merged')

            if [ "$PR_STATUS" != "true" ]; then
              ALL_MERGED=false
              echo "Related PR $PR_NUMBER in repository $REPO_FULL_NAME is NOT merged."
            else
              echo "Related PR $PR_NUMBER in repository $REPO_FULL_NAME is merged."
            fi
          done

          if [ "$ALL_MERGED" != "true" ]; then
            echo "Not all related PRs are merged. Failing the check."
            exit 1
          fi
